import offers from '#tc-offers/addon.js';

const categories = offers.categories;

categories.Item({ id: 1, slug: 'letovanje', icon: 'wb_sunny', title: 'Letovanje', description: 'Sunce, more i plaže za savršen odmor', image: 'https://images.pexels.com/photos/1174732/pexels-photo-1174732.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 2, slug: 'evropski-gradovi', icon: 'location_city', title: 'Evropski gradovi', description: 'Otkrijte čari evropskih metropola', image: 'https://images.pexels.com/photos/2570063/pexels-photo-2570063.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 3, slug: 'zimovanje', icon: 'ac_unit', title: 'Zimovanje', description: 'Skijališta i zimski centri za nezaboravan odmor', image: 'https://images.pexels.com/photos/848599/pexels-photo-848599.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 4, slug: 'daleka-putovanja', icon: 'flight', title: 'Daleka putovanja', description: 'Egzotične destinacije širom sveta', image: 'https://images.pexels.com/photos/2325446/pexels-photo-2325446.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 5, slug: 'krstarenja', icon: 'directions_boat', title: 'Krstarenja', description: 'Luksuzna putovanja morem i rekama', image: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 6, slug: 'wellness', icon: 'spa', title: 'Wellness', description: 'Opuštanje, banje i spa centri', image: 'https://images.pexels.com/photos/3757942/pexels-photo-3757942.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 7, slug: 'putovanja-za-mlade', icon: 'group', title: 'Putovanja za mlade', description: 'Avanture i zabava za mlađe generacije', image: 'https://images.pexels.com/photos/2422259/pexels-photo-2422259.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 8, slug: 'poklonicka-putovanja', icon: 'church', title: 'Poklonička putovanja', description: 'Manastiri, crkve i sveta mesta', image: 'https://images.pexels.com/photos/2832034/pexels-photo-2832034.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 9, slug: 'first-minute', icon: 'flash_on', title: 'First minute', description: 'Rane rezervacije po povoljnim cenama', image: 'https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 10, slug: 'last-minute', icon: 'timer', title: 'Last minute', description: 'Ponude u poslednjem trenutku', image: 'https://images.pexels.com/photos/1450353/pexels-photo-1450353.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 11, slug: 'izleti-evropa', icon: 'tour', title: 'Izleti - Evropa', description: 'Jednodnevni i vikend izleti po Evropi', image: 'https://images.pexels.com/photos/2108845/pexels-photo-2108845.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 12, slug: 'izleti-srbija', icon: 'landscape', title: 'Izleti - Srbija', description: 'Otkrijte lepote Srbije', image: 'https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 13, slug: 'srbija', icon: 'flag', title: 'Srbija', description: 'Odmor u našoj lepoj zemlji', image: 'https://images.pexels.com/photos/2559941/pexels-photo-2559941.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 14, slug: 'nova-godina', icon: 'celebration', title: 'Nova godina', description: 'Dočekajte Novu godinu na poseban način', image: 'https://images.pexels.com/photos/1809347/pexels-photo-1809347.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 15, slug: 'sretenje', icon: 'star', title: 'Sretenje', description: 'Praznična putovanja za Dan državnosti', image: 'https://images.pexels.com/photos/3617500/pexels-photo-3617500.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 16, slug: 'dan-zena', icon: 'favorite', title: 'Dan žena - 8. mart', description: 'Posebne ponude za 8. mart', image: 'https://images.pexels.com/photos/1024960/pexels-photo-1024960.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 17, slug: 'uskrs', icon: 'egg', title: 'Uskrs', description: 'Praznična putovanja za Uskrs', image: 'https://images.pexels.com/photos/5875034/pexels-photo-5875034.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 18, slug: 'prvi-maj', icon: 'nature', title: 'Prvi Maj', description: 'Prvomajski izleti i odmor', image: 'https://images.pexels.com/photos/1268855/pexels-photo-1268855.jpeg?auto=compress&cs=tinysrgb&w=800' });
categories.Item({ id: 19, slug: 'dan-primirja', icon: 'military_tech', title: 'Dan primirja', description: 'Putovanja za novembarske praznike', image: 'https://images.pexels.com/photos/933054/pexels-photo-933054.jpeg?auto=compress&cs=tinysrgb&w=800' });
